[workspace]
resolver = "3"
members = ["asio", "crates/acx-sys", "crates/ak1-proto", "driver/ak1-acx", "tools/ak1-asio-host", "tools/ak1-probe"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.metadata.wdk.driver-model]
driver-type = "KMDF"
kmdf-version-major = 1
target-kmdf-version-minor = 33

[workspace.dependencies]
wdk = "0.4.1"
wdk-alloc = "0.4.1"
wdk-build = "0.5.1"
wdk-panic = "0.4.1"
wdk-sys = "0.5.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
