[package]
name = "acx-sys"
edition.workspace = true
license.workspace = true
version.workspace = true
links = "acxstub"

# Kernel-mode code; a user-mode test binary cannot link against it.
[lib]
test = false
doctest = false

[dependencies]
paste = "1.0.15"
wdk-sys.workspace = true

[build-dependencies]
bindgen = "0.71.1"
wdk-build.workspace = true
